name: Android

on: 
  workflow_dispatch:
  push:
   branches:
     - main

jobs:
  buildAndroid:
    runs-on: windows-latest

    steps:
      - name: Checkout reposity
      - uses: actions/checkout@v2

      