name: CI

on:
  workflow_dispatch:

jobs:
  androidBuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [release, debug]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.2.5

      - name: Install Haxelibs
        run: |
          haxelib --quiet install lime 7.9.0
          haxelib --quiet install openfl 9.1.0
          haxelib --quiet install flixel 4.11.0
          haxelib --quiet install flixel-ui 2.5.0
          haxelib --quiet install flixel-addons 3.0.2
          haxelib --quiet install hxcpp 4.3.0
          haxelib set lime 7.9.0
          haxelib set openfl 9.1.0
          haxelib set flixel 4.11.0

      - name: Configure Lime Target
        run: |
          mkdir -p ~/.lime
          cat << EOF > ~/.lime/config.xml
          <?xml version="1.0" encoding="utf-8"?>
          <config>
            <section id="android">
              <path id="ANDROID_SDK" value="${ANDROID_HOME}" />
              <path id="ANDROID_NDK_ROOT" value="${{ steps.setup-ndk.outputs.ndk-path }}" />
              <path id="JAVA_HOME" value="${JAVA_HOME}" />
            </section>
            <define name="android" />
          </config>
          EOF

      - name: Compile
        env:
          ANDROID_SDK: ${{ env.ANDROID_HOME }}
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: haxelib run lime build android -${{ matrix.arch }} -Dno-pch

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: androidBuild-${{ matrix.arch }}
          path: export/${{ matrix.arch }}/android/bin/app/build/outputs/apk/${{ matrix.arch }}/*.apk